apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 32000
    protocol: TCP
  selector:
    app: spring-app
    